spring.application.name=ErrorHandler

# Habilitar/deshabilitar el filtro (por defecto está habilitado)
logging.filter.enabled=true

# Rutas a excluir del logging (por ejemplo, actuator, swagger, etc.)
logging.filter.exclude-paths=/actuator/health,/v3/api-docs,/swagger-ui.html,/favicon.ico

# Headers de la petición que quieres registrar
logging.filter.request-headers=Authorization,Content-Type,Accept,X-Request-ID

# Headers de la respuesta que quieres registrar
logging.filter.response-headers=Content-Type,X-Response-ID